import re

with open('arcade/wordle/index.html', 'r', encoding='utf-8') as f:
    content = f.read()

# Extract current words
m = re.search(r'var VALID_WORDS = \[(.*?)\];', content, re.DOTALL)
current = set(re.findall(r'"([A-Z]+)"', m.group(1)))

# Extract answer words
m2 = re.search(r'var ANSWER_WORDS = \[(.*?)\];', content, re.DOTALL)
answers = set(re.findall(r'"([A-Z]+)"', m2.group(1)))

# Comprehensive 5-letter English words
extra_words = """
ABACI ABASH ABATE ABBEY ABBOT ABETS ABHOR ABIDE ABLED ABLER ABODE ABORT ABOUT ABOVE
ABUSE ABYSS ACHED ACHES ACIDS ACING ACMES ACORN ACRES ACRID ACTED ACTOR ACUTE ADAGE
ADAPT ADDED ADDER ADEPT ADIEU ADMIN ADMIT ADOBE ADOPT ADORE ADORN ADULT AEGIS AERIE
AFFIX AFIRE AFOOT AFTER AGAIN AGATE AGAVE AGENT AGILE AGING AGLOW AGONY AGREE AHEAD
AIDED AIDER AIMED AIRED AISLE ALARM ALBUM ALDER ALERT ALGAE ALIBI ALIEN ALIGN ALIKE
ALIVE ALLAY ALLEY ALLOT ALLOW ALLOY ALOFT ALONE ALONG ALOOF ALOUD ALPHA ALTAR ALTER
AMASS AMAZE AMBER AMBLE AMEND AMINE AMINO AMISS AMITY AMONG AMPLE AMUSE ANGEL ANGER
ANGLE ANGRY ANGST ANIME ANKLE ANNEX ANNOY ANTIC ANVIL AORTA APART APHID APPLE APPLY
APRON ARBOR ARCED ARENA ARGUE ARISE ARMOR AROMA AROSE ARRAY ARROW ARSON ASHEN ASIDE
ASKED ASSET ATLAS ATONE ATTIC AUDIO AUDIT AUGUR AUNTY AVAIL AVERT AVOID AWAIT AWAKE
AWARD AWARE AWFUL AWOKE AXIAL AXIOM AZURE BABEL BACKS BACON BADGE BADLY BAGEL BAGGY
BAKED BAKER BALER BALMY BANAL BANDS BANDY BANJO BANKS BARON BASAL BASED BASIC BASIL
BASIN BASIS BATCH BATHS BATON BAYOU BEACH BEADS BEADY BEAMS BEANS BEARD BEARS BEAST
BEATS BEECH BEEFY BEERS BEGAN BEGIN BEGUN BEING BELLS BELLY BELOW BELTS BENCH BENDS
BERRY BERTH BEVEL BIBLE BIDDY BIKER BIKES BILLS BILLY BINGE BIOME BIRCH BIRDS BIRTH
BISON BLACK BLADE BLAME BLAND BLANK BLARE BLAST BLAZE BLEAK BLEAT BLEED BLEND BLESS
BLIMP BLIND BLISS BLITZ BLOAT BLOCK BLOKE BLOND BLOOD BLOOM BLOWN BLUES BLUFF BLUNT
BLURT BLUSH BOARD BOAST BOATS BOBBY BOGGY BOLTS BOMBS BONDS BONES BONUS BOOKS BOOST
BOOTH BOOTS BOOZE BORED BORNE BOSOM BOSSY BOTCH BOUND BOWED BOWLS BOXER BOXES BRACE
BRAID BRAIN BRAKE BRAND BRASS BRAVE BRAVO BRAWL BRAWN BREAD BREAK BREED BRIAR BRIBE
BRICK BRIDE BRIEF BRINE BRING BRINK BRINY BRISK BROAD BROIL BROKE BROOK BROOM BROTH
BROWN BRUNT BRUSH BRUTE BUDDY BUDGE BUGGY BUILD BUILT BULBS BULGE BULKY BULLY BUMPS
BUMPY BUNCH BUNNY BURNS BURST BUSES BUTTE BUYER BYLAW BYWAY CABIN CABLE CACHE CACTI
CADDY CADET CAFES CAGED CAGES CAKES CALLS CALMS CALVE CAMEL CAMEO CAMPS CANAL CANDY
CANES CANNY CANOE CAPER CARDS CARED CARES CARGO CAROL CARRY CARVE CASES CATCH CATER
CAUSE CAVES CEASE CEDAR CENTS CHAFE CHAIN CHAIR CHALK CHAMP CHANT CHAOS CHAPS CHARD
CHARM CHART CHASE CHEAP CHEAT CHECK CHEEK CHEER CHESS CHEST CHICK CHIEF CHILD CHILI
CHILL CHIME CHIMP CHINA CHIPS CHIRP CHOIR CHORD CHORE CHOSE CHOPS CHUNK CHURN CIDER
CIGAR CINCH CITED CIVIC CIVIL CLAIM CLAMP CLANG CLANK CLAPS CLASH CLASP CLASS CLAWS
CLAYS CLEAN CLEAR CLEFT CLERK CLICK CLIFF CLIMB CLING CLINK CLIPS CLOAK CLOCK CLONE
CLOSE CLOTH CLOUD CLOUT CLOWN CLUBS CLUCK CLUES CLUMP CLUNG COACH COALS COAST COATS
COBRA COCOA CODED CODES COILS COINS COLDS COLON COLOR COMBO COMES COMIC COMMA CONCH
CONES COOKS CORAL CORDS CORES COUCH COULD COUNT COUPE COURT COVER COYPU CRACK CRAFT
CRAMP CRANE CRANK CRASH CRATE CRAVE CRAWL CRAZE CRAZY CREAK CREAM CREEK CREEP CREST
CREWS CRICK CRIME CRIMP CRISP CROAK CROCK CRONE CROOK CROPS CROSS CROWD CROWN CRUDE
CRUEL CRUSH CRUST CRYPT CUBES CUBIC CUFFS CUMIN CURBS CURED CURES CURLS CURLY CURRY
CURSE CURVE CYCLE CYNIC DADDY DAILY DAIRY DAISY DANCE DANDY DARES DARKS DARTS DATED
DATES DAWNS DEALS DEALT DEATH DEBIT DEBUT DECAL DECAY DECKS DECOR DECOY DECRY DEEDS
DEEMS DEFER DEITY DELAY DELTA DELVE DEMON DEMUR DENIM DENSE DEPOT DEPTH DERBY DESKS
DETER DETOX DEUCE DEVIL DIALS DIARY DIETS DIGIT DIMLY DIMES DINED DINER DINES DINGY
DIRTY DISCO DISKS DITCH DITTO DITTY DIVER DIZZY DOCKS DODGE DOING DOLLS DOMES DONOR
DOORS DOSES DOUBT DOUGH DOWNS DOWDY DOWEL DOWNY DOZEN DRAFT DRAIN DRAKE DRAMA DRANK
DRAPE DRAWL DRAWN DRAWS DREAD DREAM DRESS DRIED DRIER DRIFT DRILL DRINK DRIVE DROIT
DRONE DROOL DROOP DROPS DROVE DROWN DRUGS DRUMS DRUNK DRYER DRYLY DUCAL DUCKS DUELS
DULLY DUMMY DUMPS DUNCE DUNKS DUSKY DUSTY DUSTS DWARF DWELL DYING DYERS EAGER EAGLE
EARLY EARNS EARTH EASED EASES EASEL EATEN EATER EBONY ECLAT EDGED EDGES EDITS EDICT
EIGHT EJECT ELBOW ELDER ELECT ELITE ELOPE ELUDE EMAIL EMBER EMCEE EMERY EMPTY ENACT
ENDOW ENEMY ENJOY ENSUE ENTER ENTRY ENVOY EPOCH EQUAL EQUIP ERASE ERECT ERODE ERROR
ERUPT ESSAY ETHER ETHIC EVADE EVENT EVERY EVICT EVOKE EXACT EXALT EXAMS EXERT EXILE
EXIST EXPAT EXPEL EXTRA EXUDE EXULT FABLE FACED FACES FACTS FADED FADES FAILS FAINT
FAIRS FAIRY FAITH FALSE FALLS FAMED FANCY FANGS FARMS FATAL FATES FATTY FAULT FAUNA
FAVOR FAWNS FEAST FEATS FEEDS FEELS FEIGN FEINT FELON FENCE FENDS FERNS FERRY FETCH
FETID FEVER FEWER FIBER FIELD FIEND FIFTH FIFTY FIGHT FILES FILLS FILMS FILTH FINAL
FINCH FINDS FINED FINER FINES FIRED FIRES FIRMS FIRST FISHY FISTS FIXED FIXES FIZZY
FJORD FLACK FLAGS FLAIL FLAIR FLAKE FLAME FLANK FLAPS FLARE FLASH FLASK FLATS FLAWS
FLEAS FLECK FLEES FLEET FLESH FLIES FLICK FLIER FLING FLINT FLIPS FLOAT FLOCK FLOOD
FLOOR FLORA FLOSS FLOUR FLOUT FLOWN FLOWS FLUID FLUKE FLUNG FLUSH FLUTE FOAMS FOCAL
FOCUS FOGGY FOLDS FOLKS FOLLY FONTS FOODS FOOLS FORCE FORGE FORGO FORMS FORTE FORTH
FORTS FORTY FORUM FOULS FOUND FOURS FOWLS FOXES FOYER FRAIL FRAME FRANK FRAUD FREAK
FREED FREES FRESH FRIAR FRIED FRILL FRISK FRONT FROST FROWN FROZE FRUIT FUELS FULLY
FUMES FUNDS FUNGI FUNKY FUNNY FURRY FUSSY FUZZY GAILY GAINS GALES GAMES GANGS GASES
GATES GAUGE GAUNT GAUZE GAVEL GAZES GEARS GEEKY GENRE GERMS GHOST GIANT GIDDY GIFTS
GIRLS GIVEN GIVER GIVES GLADE GLAND GLARE GLASS GLAZE GLEAM GLEAN GLIDE GLINT GLITZ
GLOAT GLOBE GLOOM GLORY GLOSS GLOVE GLUED GLYPH GNOME GOALS GOATS GOING GOLDS GOLEM
GOLFS GOODS GOOSE GORGE GOUGE GOURD GRACE GRADE GRABS GRADS GRAFT GRAIN GRAND GRANT
GRAPE GRAPH GRASP GRASS GRATE GRAVE GRAVY GRAYS GRAZE GREAT GREED GREEN GREET GRIEF
GRIDS GRILL GRIME GRIMY GRIND GRIPE GRIPS GROAN GROIN GROOM GROPE GROSS GROUP GROUT
GROVE GROWL GROWN GROWS GRUBS GRUEL GRUFF GRUNT GUARD GUAVA GUESS GUEST GUIDE GUILD
GUILT GUISE GULCH GULLS GULLY GULPS GUMMY GURUS GUSTS GUSTY GYPSY HABIT HAIRY HALLS
HALTS HALVE HANDS HANDY HANGS HAPPY HARDY HARPS HARRY HARSH HASPS HASTE HASTY HATCH
HATED HATES HAUNT HAVEN HAVOC HAWKS HAZEL HEADS HEALS HEAPS HEARD HEARS HEART HEATS
HEAVY HEDGE HEEDS HEELS HEFTY HEIST HELLO HELPS HENCE HERBS HERDS HERON HIKER HILLS
HILLY HINGE HINTS HIPPO HIRED HITCH HOARD HOBBY HOLDS HOLES HOLLY HOMER HOMES HONEY
HONOR HOOKS HOPED HOPES HORDE HORNS HORSE HOTEL HOUND HOURS HOUSE HOVER HUFFS HULKS
HUMAN HUMID HUMOR HUMPH HUMPS HUMUS HUNCH HUNTS HURLS HURRY HURTS HUSKY HYENA HYPER
ICING IDEAL IDEAS IDIOT IMAGE IMAGO IMBUE IMPEL IMPLY INANE INCUR INDEX INEPT INERT
INFER INKED INNER INPUT INTER INTRO IONIC IRATE IRONY ISSUE ITEMS IVORY JACKS JAILS
JAZZY JEANS JELLY JENNY JERKS JERKY JEWEL JIFFY JIMMY JOINS JOINT JOKER JOKES JOLLY
JOUST JUDGE JUICE JUICY JUMBO JUMPS JUMPY JUROR KAYAK KEBAB KEEPS KHAKI KICKS KILLS
KINDS KINGS KIOSK KITES KITTY KNACK KNEAD KNEEL KNEES KNELT KNIFE KNOBS KNOCK KNOLL
KNOTS KNOWN KOALA KUDOS LABEL LABOR LACKS LADEN LADLE LAKES LAMPS LANCE LANDS LANES
LARGE LASER LASSO LASTS LATCH LATER LATHE LAUGH LAYER LEACH LEADS LEAKS LEAPS LEARN
LEASE LEASH LEAST LEAVE LEDGE LEFTS LEGAL LEMON LEMUR LENDS LEVEL LEVER LIBEL LIFTS
LIGHT LIKED LILAC LIMBO LIMBS LIMED LIMES LIMIT LINEN LINER LINES LINGO LINKS LIONS
LISTS LITER LIVED LIVER LIVES LLAMA LOADS LOANS LOBBY LOCAL LOCKS LOCUS LODGE LOFTY
LOGIC LOOKS LOOPS LOOSE LORDS LORRY LOSES LOTUS LOVED LOVER LOVES LOWER LOYAL LUCKS
LUCKY LUMEN LUMPS LUMPY LUNAR LUNCH LUNGE LUNGS LURCH LYING LYRIC MACHO MACRO MADLY
MAGIC MAGMA MAIDS MAILS MAINS MAJOR MAKER MAKES MALES MALLS MAMBO MANES MANGO MANIA
MANNA MANOR MAPLE MARCH MARKS MARSH MASKS MASON MATCH MATES MATTE MAYBE MAYOR MEADS
MEALY MEALS MEANS MEDAL MEDIA MEDIC MEETS MELDS MELON MELTS MENDS MENUS MERCY MERGE
MERIT MERRY MESAS MESSY METAL METER MICRO MIGHT MILES MILLS MIMIC MINCE MINDS MINED
MINER MINES MINOR MINUS MINTS MIRTH MISER MISTY MIXED MIXER MIXES MOANS MOCHA MOCKS
MODEL MODEM MODES MOGUL MOIST MOLAR MOLDS MOLES MONEY MONKS MONTH MOODS MOODY MOONS
MOORS MOOSE MORAL MORPH MOSSY MOTEL MOTIF MOTOR MOTTO MOUND MOUNT MOURN MOUSE MOUTH
MOVER MOVES MOVIE MOWER MUDDY MULES MUMMY MUNCH MURAL MURKY MUSIC MUSKY MUSTY MUTED
MYTHS NAILS NAIVE NAKED NAMED NAMES NANNY NAPES NASTY NATAL NAVAL NAVEL NEARS NECKS
NEEDS NERVE NESTS NEVER NEWLY NICHE NIGHT NINTH NOBLE NODES NOISE NOISY NOMAD NORMS
NORTH NOSES NOTCH NOTED NOTES NOVEL NUDES NUDGE NURSE NUTTY NYLON OASIS OATHS OCCUR
OCEAN OFFER OFTEN OLIVE ONION ONSET OPENS OPERA OPTED OPTIC ORBIT ORDER OTHER OTTER
OUGHT OUNCE OUTDO OUTER OVALS OVENS OVERT OVOID OWNED OWNER OXIDE OZONE PACED PACKS
PACTS PADDY PAGAN PAGES PAILS PAINS PAINT PAIRS PALES PALMS PANEL PANES PANIC PANSY
PANTS PAPER PARKS PARSE PARTS PARTY PASTE PASTY PATCH PATHS PATIO PAUSE PAVED PEACE
PEACH PEAKS PEARL PEARS PECAN PEDAL PEEKS PEELS PEERS PENNY PERCH PERIL PERKY PETAL
PETTY PHASE PHONE PHOTO PIANO PICKS PIECE PIETY PIGGY PILED PILES PILLS PILOT PINES
PINKS PIOUS PIPES PITCH PIVOT PIXEL PIXIE PIZZA PLACE PLAID PLAIN PLANE PLANK PLANS
PLANT PLATE PLATS PLAYS PLAZA PLEAD PLEAS PLEAT PLIED PLIER PLODS PLOTS PLOWS PLUCK
PLUGS PLUMB PLUME PLUMP PLUMS PLUNK PLUSH POACH POEMS POETS POINT POISE POKER POLAR
POLES POLLS POOCH PONDS POOLS POPES POPPY PORCH PORED PORES PORKY PORTS POSED POSER
POSES POSSE POSTS POUCH POULT POUND POURS POWER PRANK PRAWN PRAYS PRESS PREYS PRICE
PRIDE PRIED PRIME PRINT PRIOR PRISM PRIVY PRIZE PROBE PRONE PRONG PROOF PROSE PROUD
PROVE PROWL PRUDE PRUNE PSALM PUDGY PULLS PULSE PUMPS PUNCH PUPIL PUPPY PURGE PURRS
PURSE PUTTS PUTTY QUAIL QUAKE QUALM QUART QUEEN QUERY QUEST QUEUE QUICK QUIET QUILL
QUILT QUIRK QUITE QUOTA QUOTE QUOTH RABBI RACED RACES RACKS RADAR RADIO RAFTS RAGED
RAGES RAIDS RAILS RAINY RAISE RAKED RAKES RALLY RAMPS RANCH RANGE RANKS RAPID RATES
RATIO RAVED RAVEN RAVES REACH REACT READS READY REALM REBEL REEDS REEFS REELS REIGN
RELAX RELAY REMIT RENEW RENTS REPAY REPEL REPLY RESIN RETRO REVEL RIDER RIDES RIDGE
RIFLE RIGHT RIGID RIGOR RINGS RINSE RIOTS RISES RISKY RISKS RITZY RIVAL RIVER RIVET
ROADS ROACH ROAMS ROARS ROAST ROBES ROBIN ROBOT ROCKS ROCKY RODEO ROGER ROGUE ROLES
ROLLS ROMAN ROOMS ROOST ROOTS ROPES ROSES ROUGE ROUGH ROUND ROUTE ROVER ROWDY ROYAL
RUGBY RUINS RULED RULER RULES RUMBA RUMOR RUNES RUNGS RURAL RUSTS RUSTY SACKS SADLY
SAFES SAGES SAILS SAINT SAKES SALAD SALES SALON SALSA SALTS SALTY SALVE SANDS SANDY
SAUCE SAUCY SAUNA SAVED SAVES SAVOR SAVVY SCALD SCALE SCALP SCAMS SCANS SCARE SCARF
SCARY SCENE SCENT SCOFF SCOLD SCONE SCOOP SCOPE SCORE SCORN SCOUT SCOWL SCRAM SCRAP
SCREW SCRUB SEALS SEAMS SEATS SEEDS SEEKS SEEMS SEEPS SEIZE SELLS SENDS SENSE SERVE
SETUP SEVEN SEVER SEWED SEWER SHADE SHADY SHAFT SHAKE SHALL SHAME SHAPE SHARD SHARE
SHARK SHARP SHAVE SHAWL SHEAR SHEDS SHEEN SHEEP SHEER SHEET SHELF SHELL SHIFT SHINE
SHINY SHIPS SHIRE SHIRT SHOCK SHOOT SHOPS SHORE SHORT SHOTS SHOUT SHOVE SHOWN SHOWS
SHOWY SHRUB SHRUG SHUCK SHUNT SHUTS SIDES SIEGE SIGHT SIGMA SIGNS SILLY SILKS SILLS
SILTS SINCE SINKS SIRED SIREN SIRES SITES SIXTH SIXTY SIZED SIZES SKATE SKIED SKIES
SKILL SKIMP SKINS SKIPS SKIRT SKULL SKUNK SLACK SLABS SLAGS SLAIN SLAMS SLANG SLANT
SLAPS SLASH SLATE SLATS SLAVE SLEDS SLEEK SLEEP SLEET SLICE SLIDE SLIME SLIMY SLING
SLINK SLIPS SLITS SLOPE SLOTH SLOTS SLUGS SLUMP SLUMS SLUNG SLUNK SLURP SMALL SMART
SMASH SMEAR SMELL SMILE SMIRK SMITE SMITH SMOCK SMOKE SMOKY SNACK SNAGS SNAIL SNAKE
SNAPS SNARE SNARL SNEAK SNEER SNIDE SNIFF SNORE SNORT SNOUT SNOWY SOAKS SOAPY SOAPS
SOARS SOBER SOCKS SOILS SOLAR SOLED SOLES SOLID SOLVE SONGS SONIC SORRY SORTS SOULS
SOUND SOUPS SOUTH SPACE SPADE SPANS SPARE SPARK SPARS SPATS SPAWN SPEAK SPEAR SPECK
SPECS SPEED SPELL SPEND SPENT SPICE SPICY SPIED SPIKE SPILL SPINE SPLIT SPOKE SPOOF
SPOOK SPOOL SPOON SPORT SPOTS SPOUT SPRAY SPREE SPRIG SPUNK SPURN SPURS SQUAD SQUAT
SQUID STACK STAFF STAGE STAID STAIN STAIR STAKE STALE STALK STALL STAMP STAND STANK
STARE STARK START STASH STATE STAVE STAYS STEAK STEAL STEAM STEEL STEEP STEER STEMS
STEPS STERN STEWS STICK STIFF STILL STING STINK STINT STOCK STOIC STOKE STOLE STOMP
STONE STOOD STOOL STOOP STOPS STORE STORK STORM STORY STOUT STOVE STRAW STRAY STRIP
STRUM STRUT STUBS STUCK STUDS STUDY STUFF STUMP STUNG STUNK STUNT STYLE SUGAR SUITE
SUITS SULKS SULKY SUNNY SUPER SURGE SUSHI SWAMP SWANK SWARM SWATH SWAYS SWEAR SWEAT
SWEEP SWEET SWELL SWEPT SWIFT SWILL SWIMS SWINE SWING SWIPE SWIRL SWOON SWOOP SWORD
SWORE SWORN SWUNG SYRUP TABBY TABLE TABOO TACIT TACKS TAFFY TAILS TAINT TAKEN TAKER
TALES TALKS TALON TAMED TAMES TANGO TANGY TANKS TAPES TARDY TASKS TASTE TASTY TAUNT
TAWNY TAXES TEACH TEAMS TEARS TEETH TELLS TEMPO TEMPT TENDS TENET TENOR TENTH TEPEE
TEPID TERMS TERRA TERSE TESTS TEXTS THEFT THEIR THEME THERE THESE THICK THIEF THIGH
THING THINK THIRD THORN THOSE THREE THREW THROW THRUM THUMB THUMP TIDAL TIGER TIGHT
TILED TILES TILLS TIMER TIMID TIMES TINTS TIPSY TIRED TIRES TITAN TITLE TOAST TODAY
TOKEN TOLLS TONAL TONED TONES TOOLS TOOTH TOPAZ TOPIC TORCH TOTAL TOTES TOUCH TOUGH
TOURS TOWEL TOWER TOWNS TOXIC TRACE TRACK TRADE TRAIL TRAIN TRAIT TRAMP TRAPS TRASH
TRAWL TRAYS TREAD TREAT TREES TREND TRIAD TRIAL TRIBE TRICK TRIED TRIES TRIKE TRILL
TRIMS TRIPE TRIPS TRITE TROLL TROOP TROTH TROUT TRUCE TRUCK TRULY TRUMP TRUNK TRUSS
TRUST TRUTH TUBES TUCKS TUFTS TULIP TUMOR TUNER TUNES TUNIC TURBO TURNS TUSKS TUTOR
TWANG TWEAK TWEED TWEET TWICE TWINE TWIRL TWIST TYPED TYPES UDDER ULCER ULTRA UMBER
UNCLE UNDER UNDID UNDUE UNFIT UNIFY UNION UNITE UNITS UNITY UNLIT UNTIL UNWED UPPER
UPSET URBAN USAGE USERS USHER USUAL UTTER UVULA VAGUE VALES VALID VALOR VALUE VALVE
VANES VAPID VASES VAULT VAUNT VEGAN VEILS VEINS VENOM VENTS VENUE VERGE VERSE VIDEO
VIGOR VIEWS VILLA VINES VINYL VIOLA VIPER VIRAL VIRUS VISES VISIT VISOR VISTA VITAL
VIVID VIXEN VOCAL VODKA VOGUE VOICE VOTED VOTER VOTES VOUCH VOWED VOWEL VYING WACKY
WADED WADES WAGED WAGER WAGES WAGON WAILS WAIST WAITS WAIVE WAKED WALKS WALLS WANDS
WANTS WARDS WARES WARNS WARPS WARTS WASTE WATCH WATER WAVED WAVER WAVES WAXEN WEARS
WEARY WEAVE WEDGE WEEDS WEEDY WEEKS WEIGH WEIRD WELLS WHALE WHEAT WHEEL WHERE WHICH
WHIFF WHILE WHINE WHINY WHIRL WHISK WHITE WHOLE WHOSE WIDEN WIDER WIDOW WIDTH WIELD
WILLS WILTS WINCH WINDS WINDY WINES WINGS WINKS WIPES WIRED WIRES WISPS WITCH WITTY
WOKEN WOMAN WOMEN WOODS WORDS WORKS WORMS WORMY WORRY WORSE WORST WORTH WOULD WOUND
WOVEN WRATH WREAK WRECK WREST WRING WRIST WRITE WRONG WROTE YACHT YARDS YAWNS YEARN
YEARS YEAST YELLS YIELD YOUNG YOURS YOUTH ZEBRA ZEROS ZESTY ZONED ZONES
ABUTS ACHED ACRES ADEPT ADOPT ADULT AGING AIDED AIMED AIRED AISLE ALBUM ALDER ALIGN
AMBER AMEND AMONG AMPLE ANGST ANNEX ANTIC ANVIL APART ARENA AROSE ARROW ASSET ATTIC
AUNTY AVERT AWASH AZURE BADGE BADLY BAKER BARON BASIC BATCH BEACH BEAST BEGUN BENCH
BERRY BIBLE BIKES BILLS BIRDS BLADE BLAST BLEND BLESS BLOWN BOATS BOLTS BONDS BONES
BOOKS BOOTS BOUND BOXES BRAIN BRAND BRASS BREAD BREED BRICK BROAD BROOK BRUSH BUILD
BURNS BUSES CABIN CALLS CAMPS CARDS CAROL CATCH CAVES CHAIN CHEAP CHEER CHESS CHIEF
CHINA CHIPS CHOSE CHUNK CLAIM CLASS CLERK CLIFF CLONE CLUBS COALS COCOA CODED CODES
COINS COLON CONES CORAL CORES COSTS COUCH COUPE CRANE CRATE CRAWL CREEK CREEP CREWS
CROPS CRUDE CUBES CUFFS CURBS CURED CURLS DADDY DAIRY DANCE DARTS DATED DEALS DEBIT
DECAY DECKS DEFER DEMON DEPOT DERBY DESKS DETER DIGIT DINER DISKS DOLLS DOMES DONOR
DOORS DOSES DOWNS DRANK DRAWN DRAWS DRUGS DRUMS DUCKS DUELS DUMPS DUNKS DUSTS EAGER
EARNS EASED EASES EDITS ELBOW ELDER ELUDE ENACT ENSUE ENTRY ENVOY EPOCH EQUIP ERASE
ERECT ESSAY EVENT EXACT EXAMS EXILE EXIST EXPEL FACED FACTS FADED FAILS FALLS FAMED
FANGS FARMS FATES FATTY FAWNS FEATS FEEDS FEELS FELON FENDS FERNS FEVER FILED FILES
FILLS FILMS FINAL FINDS FINED FIRES FIRMS FISTS FIXED FLAGS FLAPS FLATS FLAWS FLEAS
FLECK FLEES FLIES FLINT FLIPS FLOWS FOAMS FOLDS FOLKS FONTS FOODS FOOLS FORMS FORTS
FOULS FOURS FOWLS FREED FREES FUELS FUMES FUNDS FUNKY FUZZY GAINS GALES GAMES GANGS
GASES GATES GAZES GEARS GERMS GIFTS GIRLS GIVES GOALS GOATS GOLDS GOLFS GOODS GRABS
GRADS GRAYS GRIDS GRIPS GROWS GRUBS GULCH GULLS GULPS GUSTS HABIT HALLS HALTS HANGS
HAWKS HEALS HEAPS HEARD HEARS HEATS HEEDS HEELS HELPS HERDS HILLS HINTS HIRED HOLDS
HOLES HOMES HOOKS HOPED HOPES HORNS HOURS HUFFS HULKS HUMPS HUNTS HURLS HURTS IDEAS
INKED ITEMS JACKS JAILS JEANS JERKS JOINS JOKES JUMPS KEEPS KICKS KILLS KINDS KINGS
KITES KNEES KNOBS KNOTS LACKS LAKES LAMPS LANDS LANES LASTS LEADS LEAKS LEAPS LEFTS
LENDS LIFTS LIKED LIMBS LIMED LIMES LINER LINES LINKS LIONS LISTS LITER LIVED LIVES
LOADS LOANS LOCKS LOOKS LOOPS LORDS LOSES LOVED LOVES LUCKS LUMPS LUNGS MAIDS MAILS
MAINS MAKES MALES MALLS MANES MARKS MASKS MATES MEALS MEANS MEETS MELDS MELTS MENDS
MENUS MESAS MILES MILLS MINDS MINED MINES MINTS MIXES MOANS MOCKS MODES MOLDS MOLES
MONKS MOODS MOONS MOORS MOVES MULES MYTHS NAILS NAMED NAMES NAPES NEARS NECKS NESTS
NODES NORMS NOSES NOTES NUDES OATHS OLIVE ONION OPENS OPTED OVALS OVENS OWNED PACKS
PACTS PAGES PAILS PAINS PAIRS PALES PANES PANTS PARKS PARTS PATHS PEAKS PEARS PEEKS
PEELS PEERS PICKS PILED PILES PILLS PINES PINKS PIPES PLANS PLATS PLAYS PLEAS PLODS
PLOTS PLOWS PLUGS PLUMS POEMS POETS POLES POLLS PONDS POOLS POPES PORED PORES PORTS
POSED POSES POSTS POURS PRAYS PREYS PRIED PULLS PUMPS PUTTS RACED RACES RACKS RAFTS
RAGED RAGES RAIDS RAILS RAKED RAKES RAMPS RANKS RATES RAVED RAVES READS REEDS REEFS
REELS RENTS RIDES RINGS RIOTS RISES RISKS ROADS ROAMS ROARS ROBES ROCKS ROLES ROLLS
ROOMS ROOTS ROPES ROSES RUINS RULED RULES RUNES RUNGS RUSTS SACKS SAFES SAGES SAILS
SAKES SALES SALTS SANDS SAVED SAVES SCAMS SCANS SEATS SEEDS SEEKS SEEMS SEEPS SELLS
SENDS SEWED SHEDS SHIPS SHOPS SHOTS SHOWS SHUTS SIDES SIGNS SILKS SILLS SILTS SINKS
SIRED SIRES SITES SIZES SKIED SKIES SKINS SKIPS SLABS SLAGS SLAMS SLAPS SLATS SLEDS
SLIPS SLITS SLOTS SLUGS SLUMS SNAGS SNAPS SOAKS SOAPS SOARS SOCKS SOILS SOLED SOLES
SONGS SORTS SOULS SOUPS SPANS SPARS SPATS SPECS SPOTS SPURS STARS STEMS STEPS STEWS
STOPS STUBS STUDS SUITS SULKS SWAYS SWIMS TACKS TAILS TALES TALKS TAMED TAMES TANKS
TAPES TASKS TAXES TEAMS TEARS TELLS TENDS TERMS TESTS TEXTS TILED TILES TILLS TIMES
TINTS TIRES TOLLS TONED TONES TOOLS TOTES TOURS TOWNS TRAPS TRAYS TREES TRIES TRIMS
TRIPS TUBES TUCKS TUFTS TUNES TURNS TUSKS TYPED TYPES UNITS USAGE USERS VALES VANES
VASES VEILS VENOM VENTS VIEWS VINES VISES VOTED VOTES VOWED WADED WADES WAGED WALKS
WALLS WANDS WANTS WARDS WARES WARNS WARPS WARTS WAVED WAVES WEARS WEEDS WEEKS WELLS
WILLS WILTS WINDS WINES WINGS WINKS WIPES WIRED WIRES WISPS WOODS WORDS WORKS WORMS
""".split()

# Filter to exactly 5 letters, uppercase, alpha only
extra = {w.upper() for w in extra_words if len(w) == 5 and w.isalpha()}

# Combine all
all_words = current | answers | extra
all_words = sorted({w for w in all_words if len(w) == 5 and w.isalpha() and w.isupper()})

print(f"Total words: {len(all_words)}")

# Verify all answer words included
missing = [w for w in answers if w not in set(all_words)]
print(f"Missing answers: {missing}")

# Check some key words
for w in ["CRANE","STARE","HOUSE","ABOUT","THEIR","WOULD","COULD","WHICH","THERE","WHERE"]:
    status = "OK" if w in set(all_words) else "MISSING"
    print(f"  {w}: {status}")

# Format ~15 per line
lines = []
for i in range(0, len(all_words), 15):
    chunk = all_words[i:i+15]
    lines.append("  " + ",".join(f'"{w}"' for w in chunk))

result = "var VALID_WORDS = [\n" + ",\n".join(lines) + "\n];"

# Now replace in the HTML file
# Find the exact boundaries
start_marker = "var VALID_WORDS = ["
end_marker = "];\n\nvar VALID_SET = {};"

start_idx = content.index(start_marker)
end_idx = content.index(end_marker, start_idx) + len("];")

new_content = content[:start_idx] + result + content[end_idx:]

with open('arcade/wordle/index.html', 'w', encoding='utf-8') as f:
    f.write(new_content)

print("File updated successfully!")
