import re

with open('arcade/wordle/index.html', 'r') as f:
    content = f.read()

# Get current valid words
m = re.search(r'var VALID_WORDS = \[(.*?)\];', content, re.DOTALL)
current = set(re.findall(r'"([A-Z]+)"', m.group(1)))
current = {w for w in current if len(w) == 5}

# Get answer words
m2 = re.search(r'var ANSWER_WORDS = \[(.*?)\];', content, re.DOTALL)
answer = set(re.findall(r'"([A-Z]+)"', m2.group(1)))

# Comprehensive list of common 5-letter English words (school-appropriate)
# This is a curated list of real English words
words_text = """
ABACK ABATE ABBEY ABBOT ABHOR ABIDE ABODE ABORT ABOUT ABOVE ABUSE ABYSS ACHED ACHES
ACIDS ACING ACORN ACRID ACTED ACTOR ACUTE ADAGE ADDED ADDER ADEPT ADMIN ADMIT ADOBE
ADOPT ADORE ADORN ADULT AEGIS AERIE AFFIX AFIRE AFOOT AFTER AGAIN AGATE AGAVE AGENT
AGILE AGING AGLOW AGONY AGREE AHEAD AIDED AIDER AIMED AIRED AISLE ALARM ALBUM ALDER
ALERT ALGAE ALIBI ALIEN ALIGN ALIKE ALIVE ALLAY ALLEY ALLOT ALLOW ALLOY ALOFT ALONE
ALONG ALOOF ALOUD ALPHA ALTAR ALTER AMASS AMAZE AMBER AMBLE AMEND AMINE AMINO AMISS
AMONG AMPLE AMUSE ANGEL ANGER ANGLE ANGRY ANGST ANIME ANKLE ANNEX ANNOY ANTIC ANVIL
AORTA APART APHID APPLE APPLY APRON ARBOR ARCED ARENA ARGUE ARMOR AROMA AROSE ARRAY
ARROW ARSON ASIDE ASSET ATLAS ATONE ATTIC AUDIO AUDIT AUNTY AVERT AVOID AWAIT AWAKE
AWARD AWARE AWFUL AWOKE AXIAL AXIOM AZURE BABEL BACON BADGE BADLY BAGEL BAGGY BAKER
BALER BALMY BANAL BANDY BANJO BARON BASAL BASIC BASIL BASIN BATCH BATON BAYOU BEACH
BEADY BEARD BEAST BEECH BEEFY BEGAN BEGIN BEING BELLE BELLY BELOW BENCH BERRY BEVEL
BIBLE BIKER BILLY BINGE BIOME BIRCH BIRTH BISON BLACK BLADE BLAME BLAND BLANK BLARE
BLAST BLAZE BLEAK BLEAT BLEED BLEND BLESS BLIMP BLIND BLISS BLITZ BLOAT BLOCK BLOKE
BLOND BLOOD BLOOM BLOWN BLUES BLUFF BLUNT BLURT BLUSH BOARD BOAST BOBBY BOGGY BONUS
BOOBY BOOST BOOTH BOOZE BORAX BORED BORNE BOSOM BOSSY BOTCH BOUND BOWED BOXER BRACE
BRAID BRAIN BRAKE BRAND BRASS BRAVE BRAVO BRAWL BRAWN BREAD BREAK BREED BRIAR BRIBE
BRICK BRIDE BRIEF BRINE BRING BRINK BRISK BROAD BROIL BROKE BROOK BROOD BROOM BROTH
BROWN BRUSH BRUNT BRUTE BUDDY BUDGE BUGGY BUILD BUILT BULGE BULKY BULLY BUMPY BUNCH
BUNNY BURST BUTTE BUYER BYLAW BYWAY CABIN CABLE CACTI CADDY CADET CALVE CAMEL CAMEO
CANAL CANDY CANNY CANOE CAPER CARGO CAROL CARRY CARVE CATCH CATER CAUSE CAVIL CEASE
CEDAR CHAIN CHAIR CHAFE CHALK CHAMP CHANT CHAOS CHARD CHARM CHART CHASE CHASM CHEAP
CHEAT CHECK CHEEK CHEER CHESS CHEST CHICK CHIEF CHILD CHILI CHILL CHIME CHINA CHIMP
CHIRP CHOIR CHORD CHORE CHOSE CHUNK CHURN CIDER CIGAR CINCH CIVIC CIVIL CLAIM CLAMP
CLANG CLANK CLASH CLASP CLASS CLEAN CLEAR CLEFT CLERK CLICK CLIFF CLIMB CLING CLINK
CLOAK CLOCK CLONE CLOSE CLOTH CLOUD CLOUT CLOWN CLUCK CLUMP CLUNG COACH COAST COBRA
COCOA COILS COLOR COLON COMBO COMMA COMIC CONCH CORAL CORGI COUCH COULD COUNT COUPE
COURT COVER COYPU CRACK CRAFT CRAMP CRANE CRANK CRASH CRATE CRAVE CRAWL CRAZE CRAZY
CREAK CREAM CREEK CREEP CREST CRICK CRIME CRIMP CRISP CROAK CROCK CRONE CROOK CROSS
CROWD CROWN CRUDE CRUEL CRUSH CRUST CRYPT CUBIC CUMIN CURIO CURLY CURRY CURSE CURVE
CYCLE CYNIC DADDY DAILY DAIRY DAISY DANCE DANDY DEALT DEATH DEBIT DEBUT DECAL DECAY
DECOR DECOY DECRY DEFER DEITY DELAY DELTA DELVE DEMON DEMUR DENIM DENSE DEPOT DEPTH
DERBY DETER DEUCE DEVIL DIARY DIGIT DINER DINGY DIRTY DISCO DITCH DITTO DITTY DIVER
DIZZY DODGE DOING DONOR DOUBT DOUGH DOWDY DOWEL DOWNY DOZEN DRAFT DRAIN DRAKE DRAMA
DRANK DRAPE DRAWL DRAWN DREAD DREAM DRESS DRIED DRIER DRIFT DRILL DRINK DRIVE DRONE
DROOL DROOP DROVE DROWN DRUNK DRYER DRYLY DULLY DUMMY DUNCE DUSKY DUSTY DWARF DWELL
DYING EAGER EAGLE EARLY EARTH EASEL EATEN EATER EBONY ECLAT EDGED EDICT EIGHT EJECT
ELBOW ELDER ELECT ELITE ELOPE ELUDE EMAIL EMBER EMCEE EMERY EMPTY ENACT ENDOW ENEMY
ENJOY ENNUI ENSUE ENTER ENTRY ENVOY EPOCH EQUAL EQUIP ERASE ERECT ERODE ERROR ERUPT
ESSAY ETHER ETHIC EVADE EVENT EVERY EVICT EVOKE EXACT EXALT EXERT EXILE EXIST EXPAT
EXPEL EXTRA EXUDE EXULT FABLE FACET FAINT FAIRY FAITH FALSE FANCY FATAL FAULT FAUNA
FEAST FEIGN FEINT FELON FENCE FERRY FETAL FETCH FETID FEVER FIBER FIELD FIEND FIFTH
FIFTY FIGHT FILTH FINAL FINCH FINER FIRST FISHY FIXED FIZZY FJORD FLACK FLAIL FLAIR
FLAKE FLAME FLANK FLARE FLASH FLASK FLEET FLESH FLICK FLIER FLING FLINT FLOAT FLOCK
FLOOD FLOOR FLORA FLOSS FLOUR FLOUT FLOWN FLUID FLUKE FLUNG FLUSH FLUTE FOCAL FOCUS
FOGGY FOLLY FORCE FORGE FORGO FORTE FORTH FORTY FORUM FOSSIL FOUND FOYER FRAIL FRAME
FRANK FRAUD FREAK FRESH FRIAR FRIED FRILL FRISK FRONT FROST FROZE FROWN FRUIT FULLY
FUNGI FUNKY FUNNY FURRY FUSSY FUZZY GAILY GAUGE GAUNT GAUZE GAVEL GEEKY GENRE GHOST
GIANT GIDDY GIVEN GIVER GLADE GLAND GLARE GLASS GLAZE GLEAM GLEAN GLIDE GLINT GLOAT
GLOBE GLOOM GLORY GLOSS GLOVE GLUED GLYPH GNOME GOING GOLEM GOOSE GORGE GOUGE GOURD
GRACE GRADE GRAFT GRAIN GRAND GRANT GRAPE GRAPH GRASP GRASS GRATE GRAVE GRAVY GRAZE
GREAT GREED GREEN GREET GRIEF GRILL GRIME GRIMY GRIND GRIPE GROAN GROIN GROOM GROPE
GROSS GROUP GROUT GROVE GROWL GROWN GRUEL GRUFF GRUNT GUAVA GUARD GUESS GUEST GUIDE
GUILD GUILT GUISE GULCH GULLY GUMMY GUSTY GYPSY HABIT HAIRY HALVE HANDY HAPPY HARDY
HARRY HARSH HASTE HASTY HATCH HAUNT HAVEN HAVOC HAZEL HEADS HEART HEAVY HEDGE HEFTY
HEIST HELLO HENCE HERBS HERON HIKER HILLY HINGE HIPPO HITCH HOARD HOBBY HOLLY HOMER
HONEY HONOR HORDE HORSE HOTEL HOUND HOUSE HOVER HUMAN HUMID HUMOR HUMPH HUMUS HUNCH
HURRY HUSKY HYENA HYPER ICING IDEAL IDIOT IMAGE IMAGO IMBUE IMPEL IMPLY INANE INCUR
INDEX INEPT INERT INFER INNER INPUT INTER INTRO IONIC IRATE IRONY ISSUE ITEMS IVORY
JAZZY JELLY JENNY JERKY JEWEL JIFFY JIMMY JOINT JOKER JOLLY JOUST JUDGE JUICE JUICY
JUMBO JUMPY JUROR KAYAK KEBAB KHAKI KIOSK KITTY KNACK KNEAD KNEEL KNELT KNIFE KNOCK
KNOLL KNOWN KOALA KUDOS LABEL LABOR LADEN LADLE LANCE LARGE LASER LASSO LATCH LATER
LATHE LAUGH LAYER LEACH LEARN LEASE LEASH LEAST LEAVE LEDGE LEGAL LEMON LEMUR LEVEL
LEVER LIBEL LIGHT LILAC LIMBO LIMIT LINEN LINER LINGO LIVER LLAMA LOBBY LOCAL LOCUS
LODGE LOFTY LOGIC LOOSE LORRY LOTUS LOVER LOWER LOYAL LUCID LUCKY LUMEN LUMPY LUNAR
LUNCH LUNGE LURCH LYING LYRIC MACHO MACRO MADLY MAGIC MAGMA MAJOR MAKER MAMBO MANGO
MANIA MANOR MAPLE MARCH MARSH MASON MATCH MATTE MAYBE MAYOR MEALY MEDIA MEDAL MEDIC
MELON MERCY MERGE MERIT MERRY MESSY METAL METER MICRO MIGHT MIMIC MINCE MINER MINOR
MINUS MIRTH MISER MISTY MIXER MOCHA MODEL MODEM MOGUL MOIST MOLAR MONEY MONTH MOODY
MOOSE MORAL MORPH MOSSY MOTEL MOTIF MOTOR MOTTO MOUND MOUNT MOURN MOUSE MOUTH MOVER
MOVIE MOWER MUDDY MUMMY MUNCH MURAL MURKY MUSIC MUSKY MUSTY MUTED NAIVE NAKED NAMED
NANNY NASTY NATAL NAVAL NAVEL NEEDS NERVE NEVER NEWLY NICHE NIGHT NINTH NOBLE NOISE
NOISY NOMAD NORTH NOTCH NOTED NOVEL NUDGE NURSE NUTTY NYLON OASIS OCCUR OCEAN OFFER
OFTEN OLIVE ONION ONSET OPERA OPTIC ORBIT ORDER OTHER OTTER OUGHT OUNCE OUTER OUTDO
OVERT OVOID OWNER OXIDE OZONE PACED PADDY PAGAN PAINT PALMS PANEL PANIC PANSY PAPER
PARRY PARSE PARTY PASTE PASTY PATCH PATIO PAUSE PAVED PEACE PEACH PEARL PECAN PEDAL
PENNY PERCH PERIL PERKY PETAL PETTY PHASE PHONE PHOTO PIANO PIECE PIETY PIGGY PILOT
PIOUS PITCH PIVOT PIXEL PIXIE PIZZA PLACE PLAID PLAIN PLANE PLANK PLANT PLATE PLAZA
PLEAD PLEAT PLIED PLIER PLUCK PLUMB PLUME PLUMP PLUNK PLUSH POACH POINT POISE POKER
POLAR POOCH POPPY PORCH PORKY POSER POSSE POUCH POULT POUND POWER PRANK PRAWN PRESS
PRICE PRIDE PRIED PRIME PRINT PRIOR PRIVY PRISM PRIZE PROBE PRONE PRONG PROOF PROSE
PROUD PROVE PROWL PRUDE PRUNE PSALM PUDGY PULSE PUNCH PUPIL PUPPY PURGE PURSE PUTTY
QUAIL QUAKE QUALM QUART QUEEN QUERY QUEST QUEUE QUICK QUIET QUILL QUILT QUIRK QUOTA
QUOTE QUOTH RABBI RADAR RADIO RAINY RAISE RALLY RANCH RANGE RAPID RATIO RAVEN REACH
REACT READY REALM REBEL REIGN RELAX RELAY REMIT RENEW REPAY REPEL REPLY RESIN RETRO
REVEL RIDER RIDGE RIFLE RIGHT RIGID RIGOR RINSE RISKY RITZY RIVAL RIVET RIVER ROACH
ROAST ROBIN ROBOT ROCKY RODEO ROGUE ROOST ROUGH ROUGE ROUND ROUTE ROVER ROWDY ROYAL
RUGBY RULER RUMBA RUMOR RUPEE RURAL RUSTY SADLY SAINT SALAD SALON SALSA SALTY SALVE
SANDY SAUCE SAUNA SAVOR SAVVY SCALE SCALP SCARE SCARY SCENE SCENT SCOFF SCOLD SCONE
SCOOP SCOPE SCORE SCORN SCOUT SCOWL SCRAM SCRAP SCRUB SEIZE SENSE SERVE SETUP SEVEN
SEVER SHADE SHADY SHAFT SHAKE SHALL SHAME SHAPE SHARD SHARE SHARK SHARP SHAVE SHAWL
SHEAR SHEEN SHEEP SHEER SHEET SHELF SHELL SHIFT SHINE SHINY SHIRE SHIRT SHOCK SHOOT
SHORE SHORT SHOUT SHOVE SHOWN SHOWY SHRUB SHRUG SHUCK SHUNT SIEGE SIGMA SIGHT SILLY
SINCE SIREN SISSY SIXTH SIXTY SIZED SKATE SKIMP SKIRT SKILL SKULL SKUNK SLACK SLAIN
SLANG SLANT SLASH SLATE SLAVE SLEEK SLEEP SLEET SLICE SLIDE SLIME SLIMY SLING SLINK
SLOPE SLOTH SLUMP SLUNG SLUNK SLURP SMALL SMART SMASH SMEAR SMELL SMILE SMIRK SMITE
SMITH SMOCK SMOKE SMOKY SNACK SNAIL SNAKE SNARE SNARL SNEAK SNEER SNIDE SNIFF SNORE
SNORT SNOUT SNOWY SOAPY SOBER SOLAR SOLID SOLVE SONIC SORRY SOUND SOUTH SPACE SPADE
SPARE SPARK SPAWN SPEAK SPEAR SPECK SPEED SPELL SPEND SPENT SPICE SPICY SPIED SPIKE
SPILL SPINE SPOKE SPOOF SPOOK SPOOL SPOON SPORT SPOUT SPRAY SPREE SPRIG SPUNK SPURN
SQUAD SQUAT SQUID STACK STAFF STAGE STAID STAIN STAIR STAKE STALE STALK STALL STAMP
STAND STANK STARE STARK START STASH STATE STAYS STAVE STEAK STEAL STEAM STEEL STEEP
STEER STERN STICK STIFF STILL STING STINK STINT STOCK STOIC STOKE STOLE STOMP STONE
STOOD STOOL STOOP STORE STORK STORM STORY STOUT STOVE STRAW STRAY STRIP STRUM STRUT
STUCK STUDY STUFF STUMP STUNG STUNK STUNT STYLE SUGAR SUITE SULKY SUNNY SUPER SURGE
SUSHI SWAMP SWANK SWARM SWATH SWEAR SWEAT SWEEP SWEET SWEPT SWIFT SWILL SWINE SWING
SWIPE SWIRL SWOON SWOOP SWORD SWORE SWORN SWUNG SYRUP TABBY TABLE TABOO TACIT TAFFY
TAINT TAKEN TAKER TALON TAMED TANGO TANGY TARDY TASTE TASTY TAUNT TAWNY TEACH TEETH
TEMPO TEMPT TENET TENOR TENTH TEPEE TEPID TERRA TERSE THEFT THEIR THEME THERE THESE
THICK THIEF THIGH THING THINK THIRD THORN THOSE THREE THREW THROW THUMB TIDAL TIGER
TIGHT TIMER TIMID TIPSY TIRED TITAN TITLE TOAST TODAY TOKEN TONAL TOPAZ TOPIC TORCH
TOTAL TOUCH TOUGH TOWEL TOWER TOXIC TRACE TRACK TRADE TRAIL TRAIN TRAIT TRAMP TRASH
TRAWL TREAD TREAT TREND TRIAD TRIAL TRIBE TRICK TRIED TRIKE TRILL TRIPE TRITE TROLL
TROOP TROTH TROUT TRUCE TRUCK TRULY TRUMP TRUNK TRUSS TRUST TRUTH TULIP TUMOR TUNER
TUNIC TURBO TUTOR TWANG TWEAK TWEED TWEET TWICE TWINE TWIRL TWIST UDDER ULCER ULTRA
UMBER UNCLE UNDER UNDID UNDUE UNFIT UNIFY UNION UNLIT UNITE UNITY UNTIL UNWED UPPER
UPSET URBAN USHER USUAL UTTER UVULA VAGUE VALID VALOR VALUE VALVE VAPID VAULT VAUNT
VEGAN VEINS VENUE VERGE VERSE VIDEO VIGOR VILLA VINYL VIOLA VIPER VIRAL VIRUS VISOR
VISIT VISTA VITAL VIVID VIXEN VOCAL VODKA VOGUE VOICE VOTER VOUCH VOWEL VYING WACKY
WAGER WAGON WAIST WAIVE WASTE WATCH WATER WAVER WAXEN WEARY WEAVE WEDGE WEEDY WEIGH
WEIRD WHALE WHEAT WHEEL WHERE WHICH WHILE WHIFF WHINE WHINY WHIRL WHISK WHITE WHOLE
WHOSE WIDEN WIDER WIDOW WIDTH WIELD WINCH WINDY WINGS WITCH WITTY WOKEN WOMAN WOMEN
WORLD WORMY WORRY WORSE WORST WORTH WOULD WOUND WOVEN WRACK WRATH WREAK WRECK WREST
WRING WRIST WRITE WRONG WROTE YACHT YEARN YEAST YIELD YOUNG YOURS YOUTH ZEBRA ZESTY
ABODE ADEPT AGILE ALBUM ALERT ALLOT ALOOF AMBER AMISS ANKLE APRON ARROW BADGE BASIL
BATON BEARD BILLY BLAND BLEAT BLOWN BLUFF BLURT BLUSH BOOTH BORED BOSOM BOSSY BOTCH
BRACE BRASS BRAVO BRINE BRINK BRISK BROOD BROTH BRUTE BUDDY BUDGE BUILT BULGE BULKY
BUMPY BUYER CACTI CADDY CADET CAMEO CANAL CANNY CANOE CAPER CAROL CARVE CATER CHALK
CHAMP CHANT CHARD CHART CHEAT CHEER CHICK CHILI CHIME CHIMP CHIRP CHORD CHURN CIGAR
CINCH CLAMP CLANG CLASH CLASP CLERK CLICK CLINK CLOAK CLOUT CLUMP CLUNG COBRA COCOA
COLON COMMA CONCH CORGI COUPE CRAMP CRANK CRAVE CRAWL CRAZE CREAK CREEP CREST CROCK
CRONE CROOK CRUDE CRUST CRYPT CUBIC CUMIN CURRY CURSE CYNIC DADDY DAIRY DAISY DANDY
DEALT DECAL DECAY DECOR DECRY DEFER DEITY DELVE DEMUR DENIM DEPOT DERBY DETER DEUCE
DINER DINGY DISCO DITCH DITTO DITTY DIVER DONOR DOUBT DOUGH DOWEL DRAKE DRANK DRAPE
DRAWL DREAD DRIER DRONE DROOL DROOP DRYER DRYLY DUMMY DUNCE DWARF EASEL EATEN EATER
EBONY EDGED EDICT EJECT ELDER ELOPE ELUDE EMCEE EMERY ENDOW ENNUI ENSUE ENTRY ENVOY
EPOCH EQUIP ERASE ERECT ERODE ERUPT ETHER ETHIC EVADE EVICT EVOKE EXALT EXILE EXPAT
EXPEL EXUDE EXULT FABLE FACET FAIRY FANCY FAUNA FEIGN FEINT FELON FENCE FETAL FETID
FIEND FILTH FINCH FISHY FJORD FLACK FLAIR FLAKE FLANK FLARE FLASK FLICK FLIER FLING
FLINT FLOUR FLOUT FLUID FLUKE FLUSH FLUTE FOCAL FOGGY FOLLY FORGE FORGO FORTE FOYER
FRAIL FREAK FRIAR FRIED FRILL FRISK FROZE FROWN FUNKY FUSSY GAILY GAUGE GAUNT GAUZE
GAVEL GEEKY GENRE GIDDY GIVER GLADE GLAND GLAZE GLEAM GLEAN GLINT GLOAT GLUED GLYPH
GNOME GOLEM GORGE GOUGE GOURD GRAFT GRATE GRAVY GRAZE GREED GREET GRIEF GRIME GRIMY
GRIND GRIPE GROAN GROIN GROOM GROPE GROUT GROWL GRUEL GRUFF GRUNT GUAVA GUISE GULCH
GULLY GUMMY GUSTY GYPSY HALVE HARDY HASTY HATCH HAUNT HAVOC HAZEL HEADS HEFTY HEIST
HERBS HERON HIKER HILLY HINGE HIPPO HITCH HOARD HOBBY HOLLY HOMER HORDE HOUND HUMID
HUMPH HUMUS HUNCH HUSKY HYENA ICING IDIOT IMAGO IMBUE IMPEL IMPLY INANE INCUR INEPT
INERT IONIC IRONY JENNY JERKY JIFFY JIMMY JOUST JUICY JUMPY JUROR KEBAB KHAKI KNOLL
KOALA KUDOS LADEN LADLE LASSO LATCH LATHE LEASH LEMUR LIBEL LILAC LIMBO LINER LINGO
LOBBY LOCUS LOFTY LORRY LOTUS LUCID LUMEN LUMPY LUNGE LURCH LYRIC MACHO MADLY MAGMA
MAMBO MANGO MANIA MASON MATTE MEALY MEDIC MERIT MERRY MESSY MICRO MINCE MINUS MIRTH
MISER MOCHA MODEM MOGUL MOIST MOLAR MOODY MORPH MOSSY MOTEL MOTIF MOTOR MOUND MOURN
MOVER MUDDY MUMMY MURAL MURKY MUSKY MUSTY MUTED NAIVE NATAL NAVEL NICHE NOISY NOMAD
NOTCH NYLON OPTIC OUNCE OUTDO OVERT OVOID PADDY PAGAN PALMS PANSY PARRY PARSE PASTY
PATIO PAVED PECAN PERIL PERKY PETAL PETTY PIETY PIGGY PIOUS PIVOT PIXIE PIZZA PLAID
PLANK PLEAT PLIED PLIER PLUCK PLUMB PLUMP PLUNK POACH POISE POKER POOCH POPPY PORCH
PORKY POSER POSSE POULT PRANK PRAWN PRIED PRIVY PRONE PRONG PROSE PROWL PRUDE PRUNE
PUDGY PURGE PURSE PUTTY QUAIL QUAKE QUALM QUART QUERY QUEUE QUILL QUIRK QUOTA QUOTH
RABBI RALLY REBEL REMIT RENEW REPAY REPEL RESIN RETRO REVEL RIFLE RIGOR RINSE RITZY
RIVET ROACH ROBIN RODEO ROGUE ROOST ROUGE ROVER ROWDY RUGBY RUMBA RUMOR RUPEE SADLY
SALON SALSA SALTY SALVE SAUNA SAVOR SAVVY SCALP SCARY SCENT SCOFF SCOLD SCONE SCOOP
SCORN SCOUT SCOWL SCRAM SCRAP SCRUB SEIZE SETUP SEVER SHADY SHARD SHAVE SHAWL SHEAR
SHEEN SHEEP SHEER SHIRE SHOVE SHOWY SHRUB SHRUG SHUCK SHUNT SIEGE SIGMA SILLY SIREN
SISSY SKATE SKIRT SKUNK SLACK SLAIN SLANG SLANT SLEEK SLEET SLIME SLIMY SLING SLINK
SLOTH SLUMP SLUNG SLUNK SLURP SMASH SMEAR SMIRK SMITE SMITH SMOCK SMOKY SNACK SNAIL
SNARE SNARL SNEAK SNEER SNIDE SNORE SNORT SNOUT SNOWY SOAPY SOBER SONIC SPADE SPARK
SPAWN SPEAR SPECK SPICY SPIED SPIKE SPOOF SPOOK SPOOL SPOUT SPREE SPRIG SPUNK SPURN
SQUAT SQUID STAID STAIR STALK STANK STARK STASH STAVE STEAK STEAL STERN STIFF STING
STINK STINT STOIC STOKE STOLE STOMP STOOL STOOP STORK STOUT STRAW STRAY STRUM STRUT
STUMP STUNG STUNK STUNT SULKY SUSHI SWANK SWARM SWATH SWEAT SWILL SWINE SWIPE SWOON
SWOOP SYRUP TABBY TABOO TACIT TAFFY TAINT TAKEN TAKER TAMED TANGO TANGY TARDY TAUNT
TAWNY TEMPT TENET TENOR TEPEE TEPID TERRA TERSE THIEF THIGH TIMID TIPSY TITAN TOKEN
TONAL TOPAZ TORCH TRAMP TRAWL TREAD TRIAD TRIKE TRILL TRIPE TRITE TROLL TROTH TRUCE
TRUMP TRUNK TRUSS TUNER TUNIC TURBO TUTOR TWANG TWEAK TWEED TWEET TWINE TWIRL UDDER
ULCER UMBER UNDID UNDUE UNFIT UNIFY UNLIT UNWED UVULA VAGUE VALOR VALVE VAPID VAUNT
VEGAN VEINS VERGE VILLA VINYL VIPER VISOR VIXEN VODKA VOGUE VOUCH VYING WACKY WAGER
WAIVE WAVER WAXEN WEARY WEEDY WHINE WHINY WHIRL WHISK WIDER WIDOW WIDTH WIELD WINCH
WOKEN WOMAN WOMEN WORMY WRACK WRATH WREAK WRECK WREST WRING YACHT YEARN YOURS ENACT
ALOUD AMASS DEBIT DOWNY DUSKY BEEFY BRUNT CALVE CHAFE CIVIC COILS COMBO CRICK CURIO
BUTTE BYWAY CLEFT ARCED ASHEN BLITZ BEVEL AGAVE ADDER AFIRE AGATE COYPU FLAIL BOBBY
BOGGY BORAX BOWED DULLY BAGGY BALER BANDY BAYOU BEADY BIOME BLARE BLOKE BLOAT BLUES
BLUNT BLURT BOOST BORED BORNE BOSOM BOSSY BRAID BRAVO BRAWL BRINE BRINK BROOD BROTH
BRUTE BUDGE BUGGY BULKY CACTI CADDY CALVE CAMEO CANNY CAPER CAVIL CHANT CHARD CHIRP
CLANG CLANK CLASH CLASP CLINK CLOUT CLUMP CLUNG COBRA COCOA COMMA CONCH CRAMP CRANK
CRAVE CRAWL CRAZE CREAK CREEP CROCK CRONE CROOK CRUDE CRUST CRYPT CUBIC CUMIN CYNIC
DECAL DECRY DEFER DELVE DEMUR DENIM DEPOT DERBY DETER DEUCE DINGY DITTO DITTY DOWDY
DOWEL DRAWL DRIER DROOL DROOP DRYER DRYLY DUMMY DUNCE DWARF EATER EBONY EDGED EJECT
ELDER ELOPE ELUDE EMCEE EMERY ENSUE EPOCH EQUIP ERASE ERODE ERUPT ETHER ETHIC EVADE
EVICT EVOKE EXALT EXILE EXPAT EXPEL EXUDE EXULT FACET FAUNA FEIGN FEINT FELON FETAL
FETID FIEND FILTH FINCH FISHY FJORD FLACK FLAIR FLAKE FLANK FLARE FLASK FLICK FLIER
FLING FLINT FLOUR FLOUT FLUID FLUKE FLUSH FLUTE FOGGY FOLLY FORGO FORTE FOYER FRIAR
FRIED FRILL FRISK FROZE FROWN FUNKY FUSSY GAILY GAUGE GAUNT GAUZE GAVEL GENRE GIDDY
GLADE GLAND GLEAM GLEAN GLINT GLOAT GLUED GLYPH GNOME GOLEM GORGE GOUGE GRAFT GRATE
GRAVY GRAZE GREED GREET GRIEF GRIME GRIMY GRIND GRIPE GROAN GROIN GROOM GROPE GROUT
GROWL GRUEL GRUFF GRUNT GUAVA GUISE GULCH GULLY GUMMY GUSTY GYPSY HALVE HASTY HATCH
HAUNT HAVOC HAZEL HEFTY HEIST HERBS HERON HILLY HINGE HITCH HOARD HOLLY HOMER HORDE
HUMPH HUMUS HUNCH HUSKY HYENA IDIOT IMBUE IMPEL IMPLY INANE INCUR INEPT INERT IONIC
IRONY JENNY JERKY JIFFY JIMMY JOUST JUICY JUMPY JUROR KEBAB KNOLL KOALA KUDOS LADEN
LADLE LATCH LATHE LEASH LEMUR LIBEL LILAC LIMBO LINGO LOBBY LOCUS LOFTY LORRY LOTUS
LUCID LUMEN LUMPY LUNGE LURCH LYRIC MACHO MADLY MAGMA MAMBO MANIA MATTE MEALY MEDIC
MERIT MERRY MESSY MICRO MINCE MINUS MIRTH MISER MOCHA MODEM MOGUL MOIST MOLAR MOODY
MORPH MOSSY MOTEL MOTIF MOTOR MOUND MOURN MOVER MUDDY MUMMY MURAL MURKY MUSKY MUSTY
MUTED NATAL NAVEL NICHE NOMAD NOTCH NYLON OPTIC OUNCE OUTDO OVERT OVOID PADDY PAGAN
PANSY PARRY PARSE PASTY PATIO PAVED PECAN PERIL PERKY PETAL PETTY PIETY PIGGY PIOUS
PIVOT PIXIE PLAID PLANK PLEAT PLIED PLIER PLUCK PLUMB PLUMP PLUNK POACH POISE POKER
POOCH POPPY PORCH PORKY POSER POSSE POULT PRANK PRAWN PRIED PRIVY PRONE PRONG PROSE
PROWL PRUDE PRUNE PUDGY PURGE PURSE PUTTY QUAIL QUAKE QUALM QUART QUERY QUEUE QUILL
QUIRK QUOTA QUOTH RABBI RALLY REBEL REMIT RENEW REPAY REPEL RESIN RETRO REVEL RIFLE
RIGOR RINSE RITZY RIVET ROACH ROBIN RODEO ROGUE ROOST ROUGE ROVER ROWDY RUGBY RUMBA
RUMOR RUPEE SADLY SALSA SALTY SALVE SAUNA SAVOR SAVVY SCALP SCARY SCENT SCOFF SCOLD
SCONE SCOOP SCORN SCOUT SCOWL SCRAM SCRAP SCRUB SEIZE SETUP SEVER SHADY SHARD SHAVE
SHAWL SHEAR SHEEN SHEEP SHEER SHIRE SHOVE SHOWY SHRUB SHRUG SHUCK SHUNT SIGMA SILLY
SIREN SISSY SKATE SKIRT SKUNK SLACK SLAIN SLANG SLANT SLEEK SLEET SLIME SLIMY SLING
SLINK SLOTH SLUMP SLUNG SLUNK SLURP SMASH SMEAR SMIRK SMITE SMITH SMOCK SMOKY SNACK
SNAIL SNARE SNARL SNEAK SNEER SNIDE SNORE SNORT SNOUT SNOWY SOAPY SOBER SONIC SPADE
SPARK SPAWN SPEAR SPECK SPICY SPIED SPIKE SPOOF SPOOK SPOOL SPOUT SPREE SPRIG SPUNK
SPURN SQUAT SQUID STAID STAIR STALK STANK STARK STASH STAVE STEAK STEAL STERN STING
STINK STINT STOIC STOKE STOLE STOMP STOOL STOOP STORK STOUT STRAW STRAY STRUM STRUT
STUMP STUNG STUNK STUNT SULKY SUSHI SWANK SWARM SWATH SWEAT SWILL SWINE SWIPE SWOON
SWOOP SYRUP TABBY TABOO TACIT TAFFY TAINT TAKER TAMED TANGO TANGY TARDY TAUNT TAWNY
TEMPT TENET TENOR TEPEE TEPID TERRA TERSE THIEF THIGH TIMID TIPSY TITAN TOKEN TONAL
TOPAZ TORCH TRAMP TRAWL TREAD TRIAD TRIKE TRILL TRIPE TRITE TROLL TROTH TRUCE TRUMP
TRUNK TRUSS TUNER TUNIC TURBO TUTOR TWANG TWEAK TWEED TWEET TWINE TWIRL UDDER ULCER
UMBER UNDID UNDUE UNFIT UNIFY UNLIT UNWED UVULA VAGUE VALOR VALVE VAPID VAUNT VEGAN
VEINS VERGE VILLA VINYL VIPER VISOR VIXEN VODKA VOGUE VOUCH VYING WACKY WAGER WAIVE
WAVER WAXEN WEARY WEEDY WHINE WHINY WHIRL WHISK WIDER WIDOW WIDTH WIELD WINCH WOKEN
WOMAN WOMEN WORMY WRACK WRATH WREAK WRECK WREST WRING YACHT YEARN YOURS SIEGE PIZZA
"""

words = [w.strip() for w in words_text.split() if w.strip()]
words = [w for w in words if len(w) == 5 and w.isalpha() and w.isupper()]

# Combine all
all_words_set = current | answer | set(words)
all_words = sorted(all_words_set)

# Verify all 5 letters
non_five = [w for w in all_words if len(w) != 5]
if non_five:
    print(f'ERROR non-5-letter: {non_five}')
else:
    print(f'All words are exactly 5 letters: YES')

print(f'Total unique 5-letter words: {len(all_words)}')

# Check answer words
missing_ans = answer - all_words_set
print(f'Missing answer words: {missing_ans if missing_ans else "NONE"}')

# Check all required words from user
required = [
    'CRANE','SLATE','TRACE','CRATE','STARE','RAISE','ARISE','IRATE','AUDIO','HOUSE',
    'MOUSE','ABOUT','THEIR','WOULD','COULD','WHICH','THERE','THESE','THOSE','WHERE',
    'WHILE','PLACE','LARGE','SMALL','GREAT','FIRST','AFTER','WORLD','STILL','THINK',
    'NEVER','AGAIN','MIGHT','FOUND','BRING','GOING','BEING','DOING','LIGHT','NIGHT',
    'RIGHT','SIGHT','TIGHT','FIGHT','EIGHT','HEAVY','EARLY','EVERY','HEART','LEARN',
    'POWER','WATER','MONEY','YOUNG','MUSIC','HAPPY','PARTY','STORY','STUDY','PLANT',
    'DREAM','BRAIN','CHAIN','CLAIM','DRAIN','GRAIN','PLAIN','TRAIN','TRAIL','SCALE',
    'SCARE','SPARE','STALE','STAGE','STAKE','STATE','TASTE','WASTE','CHASE','PHASE',
    'SHAME','SHAPE','SHARE','SHAKE','BRAVE','GRAVE','GRACE','SPACE','PRICE','PRIDE',
    'PRIZE','PROVE','DROVE','GROVE','GLOBE','CLOSE','CHOSE','STONE','STORE','SCORE',
    'SHORE','KNIFE','BRIDE','GUIDE','QUIET','QUITE','QUICK','THICK','DRINK','BLACK',
    'WHITE','GREEN','BROWN','CLEAR','CLEAN','BREAK','SPEAK','TREAT','SWEET','SHEET',
    'STEEL','WHEEL','SPEED','SLEEP','STEEP','CREEK','CHEEK','TEETH','FRESH','PRESS',
    'DRESS','CHESS','BLESS','CROSS','FROST','TOAST','COAST','ROAST','BLAST','FEAST',
    'BEAST','LEAST','YEAST','BEACH','TEACH','REACH','PEACH','LEACH','BUNCH','LUNCH',
    'PUNCH','HUNCH','MUNCH','JUDGE','BADGE','LEDGE','HEDGE','WEDGE','RIDGE','LODGE',
    'DODGE','BLOCK','CLOCK','FLOCK','KNOCK','STOCK','SHOCK','CORAL','MORAL','ROYAL',
    'LOYAL','MEDAL','METAL','PEDAL','LEGAL','EQUAL','FINAL','TOTAL','VITAL','FATAL',
    'NAVAL','RURAL','SOLAR','POLAR','VOCAL','LOCAL','FOCAL','TIDAL','IDEAL','TRIAL',
    'RIVAL','USUAL','ANGEL','CAMEL','JEWEL','TOWEL','VOWEL','NOVEL','LEVEL','LEVER',
    'FEVER','RIVER','LIVER','COVER','LOVER','HOVER','TOWER','LOWER','POWER','MOWER',
    'MAKER','BAKER','TAKER','LATER','WATER','PAPER','LAYER','MAYOR','MAJOR','MINOR',
    'MANOR','HUMOR','TUMOR','VIGOR','VALOR','COLOR','FAVOR','LABOR','ERROR','PRIOR',
    'INNER','UPPER','UNDER','OTHER','OUTER','ENTER','AFTER','INTER','SUPER','HYPER',
    'FIBER','CIDER','RIDER','WIDER','TIGER','LINER','MINER','DINER','FINER','TIMER',
    'SIREN','GIVEN','SEVEN','RAVEN','HAVEN','WOVEN','DOZEN','OFTEN','LEMON','MELON',
    'BARON','BISON','MASON','SALON','TALON','COLON','FELON','DEMON','UNION','ONION',
    'BACON','WAGON','KNOWN','SHOWN','GROWN','BROWN','CROWN','CLOWN','DROWN','FROWN',
    'SWORN','THORN','SHORT','SPORT','COURT','NORTH','FORTH','WORTH','EARTH','BIRTH',
    'MONTH','MOUTH','SOUTH','YOUTH','TRUTH','FAITH','DEATH','DEPTH','TENTH','FIFTH',
    'SIXTH','NINTH','PATCH','MATCH','WATCH','CATCH','BATCH','HATCH','LATCH','DITCH',
    'PITCH','TOUCH','POUCH','COUCH','GRAPH','CRAFT','DRAFT','SHAFT','SHIFT','DRIFT',
    'SWIFT','CLIFF','STAFF','STUFF','BLUFF','SKULL','SPELL','SHELL','SMELL','SWELL',
    'DWELL','SKILL','SPILL','GRILL','DRILL','CHILL','STILL','STIFF','SNIFF','WHIFF',
    'PUPPY','KITTY','BUNNY','PENNY','BERRY','FERRY','CARRY','HARRY','SORRY','WORRY',
    'HURRY','FURRY','CURRY','DAIRY','FAIRY','HAIRY','RAINY','SHINY','NOISY','DIZZY',
    'FUZZY','JAZZY','CRAZY','LUCKY','ROCKY','DUSTY','RUSTY','NASTY','TASTY','HASTY',
    'MISTY','WINDY','SANDY','CANDY','HANDY','DANDY','EMPTY','DIRTY','FIFTY','SIXTY',
    'WITTY'
]
missing_req = [w for w in required if w not in all_words_set]
if missing_req:
    print(f'Missing required ({len(missing_req)}): {missing_req}')
else:
    print(f'All {len(set(required))} unique required words present: YES')

if len(all_words) >= 2500:
    print(f'Target of 2500+ reached: YES')
else:
    deficit = 2500 - len(all_words)
    print(f'Need {deficit} more words to reach 2500')

# Format 15 words per line
lines = []
for i in range(0, len(all_words), 15):
    chunk = all_words[i:i+15]
    lines.append('  ' + ','.join(f'"{w}"' for w in chunk))

result = 'var VALID_WORDS = [\n' + ',\n'.join(lines) + '\n];'

new_content = re.sub(r'var VALID_WORDS = \[.*?\];', result, content, flags=re.DOTALL)

with open('arcade/wordle/index.html', 'w') as f:
    f.write(new_content)

print('File written successfully!')
